"""
Extract MCQs from PDFs in ../quiz pdf/ and write quiz_pdf_questions.py.
Run from repo root: python scripts/import_pdf_questions.py
"""
from __future__ import annotations

import html
import os
import re
import sys
from pathlib import Path

try:
    from pypdf import PdfReader
except ImportError:
    print("Install pypdf: pip install pypdf", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parents[1]
PDF_DIR = ROOT / "quiz pdf"
OUT = ROOT / "quiz_pdf_questions.py"

# Numbered question, four options A-D, correct answer line, reasoning
BLOCK_RE = re.compile(
    r"(?P<num>\d+)\.\s*(?P<q>.+?)\s+A\.\s*(?P<a>.+?)\s+B\.\s*(?P<b>.+?)\s+C\.\s*(?P<c>.+?)\s+D\.\s*(?P<d>.+?)\s+"
    r"Correct\s+Answer:\s*(?P<ans>.+?)\s+Reasoning:\s*(?P<reason>.+?)(?=\s+\d+\.\s|\Z)",
    re.DOTALL | re.IGNORECASE,
)


def normalize_ws(s: str) -> str:
    s = re.sub(r"\s+", " ", s).strip()
    return s


def strip_wrapping_quotes(s: str) -> str:
    s = s.strip()
    if (s.startswith("'") and s.endswith("'")) or (s.startswith('"') and s.endswith('"')):
        return s[1:-1].strip()
    return s


def norm_key(s: str) -> str:
    return normalize_ws(strip_wrapping_quotes(html.unescape(s))).lower()


def extract_pdf_text(path: Path) -> str:
    reader = PdfReader(str(path))
    parts: list[str] = []
    for page in reader.pages:
        t = page.extract_text()
        if t:
            parts.append(t)
    return "\n".join(parts)


def parse_questions(raw: str, source: str) -> list[dict]:
    raw = raw.replace("\r", "\n")
    # Help regex: ensure space before "Correct Answer" if glued
    raw = re.sub(r"(\S)(Correct\s+Answer:)", r"\1 \2", raw, flags=re.I)
    out: list[dict] = []
    seen_q: set[str] = set()

    for m in BLOCK_RE.finditer(raw):
        qtext = normalize_ws(m.group("q"))
        opts = [
            normalize_ws(m.group("a")),
            normalize_ws(m.group("b")),
            normalize_ws(m.group("c")),
            normalize_ws(m.group("d")),
        ]
        ans = normalize_ws(m.group("ans"))
        reason = normalize_ws(m.group("reason"))

        if not qtext or len(opts) != 4 or not any(opts):
            continue

        ans_key = norm_key(ans)
        correct_idx = None
        for i, o in enumerate(opts):
            if norm_key(o) == ans_key:
                correct_idx = i
                break
        # substring match if exact fail (PDF sometimes truncates)
        if correct_idx is None:
            for i, o in enumerate(opts):
                ok, ak = norm_key(o), ans_key
                if ak in ok or ok in ak:
                    correct_idx = i
                    break
        if correct_idx is None:
            continue

        q_key = norm_key(qtext)
        if q_key in seen_q:
            continue
        seen_q.add(q_key)

        safe_q = html.escape(qtext).replace("\n", "<br>")
        safe_exp = html.escape(reason)
        opt_objs = [{"text": html.escape(o), "correct": (i == correct_idx)} for i, o in enumerate(opts)]

        out.append(
            {
                "category": f"Imported ({source})",
                "question": safe_q,
                "options": opt_objs,
                "explanation": safe_exp,
            }
        )
    return out


def main():
    if not PDF_DIR.is_dir():
        print(f"Missing folder: {PDF_DIR}", file=sys.stderr)
        sys.exit(1)

    pdf_files = sorted(PDF_DIR.glob("*.pdf"))
    if not pdf_files:
        print(f"No PDFs in {PDF_DIR}", file=sys.stderr)
        sys.exit(1)

    all_rows: list[dict] = []
    seen_global: set[str] = set()

    for pdf in pdf_files:
        label = pdf.name
        try:
            text = extract_pdf_text(pdf)
        except Exception as e:
            print(f"Skip {label}: {e}", file=sys.stderr)
            continue
        rows = parse_questions(text, label)
        for r in rows:
            k = norm_key(re.sub(r"<br\s*/?>", " ", r["question"]))
            if k in seen_global:
                continue
            seen_global.add(k)
            all_rows.append(r)
        print(f"{label}: parsed {len(rows)} (unique so far: {len(all_rows)})")

    header = (
        "# Auto-generated by scripts/import_pdf_questions.py — do not edit by hand.\n"
        "# Re-run: python scripts/import_pdf_questions.py\n\n"
        "PDF_QUESTIONS = "
    )
    body = repr(all_rows)
    OUT.write_text(header + body + "\n", encoding="utf-8")
    print(f"Wrote {len(all_rows)} questions to {OUT}")


if __name__ == "__main__":
    main()
